services:
  api:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ytqa:/app/ytqa
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ytqa_cache:/tmp/ytqa_cache
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - YTQA_CACHE_DIR=/tmp/ytqa_cache
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # Set the proxy target for the Vite dev server inside the container
      - VITE_API_PROXY_TARGET=http://api:8000
      # Ensure Node runs in development mode if needed by Vite plugins/config
      - NODE_ENV=development      
    depends_on:
      - api
    container_name: ytqa_frontend

volumes:
  ytqa_cache: 