version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ytqa_cache:/tmp/ytqa_cache
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - YTQA_CACHE_DIR=/tmp/ytqa_cache
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${API_URL:-http://localhost:8000}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${API_URL:-http://localhost:8000}
    depends_on:
      - api
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/certs:/etc/nginx/certs:ro
    depends_on:
      - api
      - frontend
    restart: always

volumes:
  ytqa_cache: 