services:
  api:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ytqa:/app/ytqa
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ytqa_cache:/tmp/ytqa_cache
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - YTQA_CACHE_DIR=/tmp/ytqa_cache
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dev.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://api:8000
    depends_on:
      - api

volumes:
  ytqa_cache: 